---
- name: deploy NSX-T Manager OVA
  nsxt_deploy_ova:
    ovftool_path: "/usr/bin"
    path_to_ova: "{{ nsxt_ova_path }}"
    ova_file: "{{ nsxt_ova_filename }}"
    vcenter: '{{ lookup("env", "VMWARE_HOST") }}'
    vcenter_user: '{{ lookup("env", "VMWARE_USER") }}'
    vcenter_passwd: '{{ lookup("env", "VMWARE_PASSWORD") }}'   
    datacenter: "{{ nsx_node1.nsxt_deployment_datacenter }}"
    cluster: "{{ nsx_node1.nsxt_deployment_cluster }}"
    datastore: "{{ nsx_node1.nsxt_deployment_datastore }}"
    portgroup: "{{ nsx_node1.nsxt_deployment_portgroup }}"  
    vmname: "{{ nsx_node1.hostname |upper }}"
    hostname: "{{ nsx_node1.hostname }}"
    dns_server: "{{ dns_server_1 }}"
    dns_domain: "{{ dns_default_domain }}"
    ntp_server: "{{ ntp_server_default }}"
    gateway: "{{ nsxt_network_gateway }}"
    ip_address: "{{ nsx_node1.nsxt_network_ip_address }}"
    netmask: "{{ nsxt_network_netmask }}"
    admin_password: "{{ nsxt_admin_password }}"
    cli_password: "{{ nsxt_cli_password }}"    
    deployment_size: "{{ nsxt_deployment_size }}"
    ssh_enabled: "{{ nsxt_ssh_enabled }}"
    role: "{{ nsxt_role }}"

- name: Check NSX-T Manager Status
  include_role:
    name: nsxt_check_manager_status
