---



# Site A CMP NSX-T Deployment Details
nsxt_datastore: "vsanDatastore"
nsxt_portgroup: "Management"
nsxt_network_ip_address: "10.1.10.16"
nsxt_network_netmask: "255.255.255.0"
nsxt_network_gateway: "10.1.10.254"

# Site A CMP vCenter Server and Cluster Details
nsxt_compute_manager_name: "{{ site_name }} CMP vCenter Server"
nsxt_compute_manager_host: sg1-vsa002.sgroot.local
nsxt_transport_clusters:
- SITEA-CLS-CLOUD-01

# Transport Zone and Profile Details
nsxt_transport_zone_name: "{{ site_name }}-CMP-Transport"
nsxt_transport_zone_desc: "Transport Zone for {{ site_name }} Cloud Resource Cluster."
nsxt_transport_node_profile_name: "{{ nsxt_transport_zone_name }}-Profile"

# Transport Switch vmknic IP Address Pool Details
nsxt_transport_switch_ip_pool_name: "{{ nsxt_transport_zone_name }}-Pool"
nsxt_transport_switch_ip_pool_start: "10.1.111.10"
nsxt_transport_switch_ip_pool_end: "10.1.111.19"
nsxt_transport_switch_ip_pool_cidr: "10.1.111.0/24"

# Transport Switch Details
nsxt_transport_switch_name: "{{ nsxt_transport_zone_name }}-Switch"
nsxt_transport_switch_uplink_profile_name: dualUplinkProfile
nsxt_transport_switch_uplink_profile_policy: FAILOVER_ORDER
nsxt_transport_switch_uplink_profile_vlan: 0
nsxt_transport_switch_profile_desc: "Transport Node Profile for {{ site_name }} Cloud Resource Cluster."
nsxt_transport_switch_pnic_1: vmnic2
nsxt_transport_switch_pnic_2: vmnic4
nsxt_transport_switch_uplink_1: uplink-1
nsxt_transport_switch_uplink_2: uplink-2
